[[columns]]
key = "period_votes"
label = "Votes"
type = "text"

[[columns]]
key = "atr"
label = "ATR"
type = "number"
decimals = 6

[[columns]]
key = "risk_atr"
label = "Risk ATR"
type = "number"
decimals = 6

[[columns]]
key = "htf_ma"
label = "D1 MA50"
type = "number"
decimals = 6

[[columns]]
key = "catastrophe"
label = "Cat Stop"
type = "number"
decimals = 6
